### ISSUE TITLE
Color Matching

### ISSUE THREAD

**Issue by baxter40** [Narochno/Narochno.BBCode#2]
Currently the parser does not convert `[color][/color]` or `[style color][/style]` tags

**Comment by alanedwardes** [comment]
@baxter40 Hi, would you mind adding the exact BBCode sample(s) and the HTML you expect as output for each one?

**Comment by baxter40** [comment]
@alanedwardes 
`[color=red]red[/color]` to `<span style="color: red">red</span>`
`[style color=#DB7900]whatever[/style]` to `<span style="color: #DB7900">whatever</span>`

Both examples taken from https://www.bbcode.org/examples/?id=6

**Comment by alanedwardes** [comment]
See https://github.com/Narochno/Narochno.BBCode/pull/3 - added to the default tags and added unit tests. Let me know if this behaviour is what you expected and i'll merge this + push `2.1.0`.

**Comment by baxter40** [comment]
@alanedwardes Looks good, thanks for the quick reply!

**Comment by alanedwardes** [comment]
Sure! @baxter40 https://www.nuget.org/packages/Narochno.BBCode/2.1.0
